# main config

# API settings
api_url: "https://testnet.binancefuture.com"  # testnet 4 futures

# dims 4 obs and act
obs_dim: 90
act_dim: 3

trade_fraction: .1
transaction_cost: .002
stop_loss_ratio: .05
take_profit_ratio: .10
initial_cash: 10000.0
max_drawdown: .20

# params 4 training
learning_rate: 0.025
#100000
total_timesteps: 40000
trading_interval: 10  # s

rllib:
  framework: "torch"
  num_gpus: 1
  num_workers: 1

horizon: 500

# logging lvl
log_level: "INFO"

data_file: "data/processed/1h.csv"